version: "3"

services:
  core:
    build: 
      context: ./packages/core
    ports:
      - "8080:8080"
    env_file:
      - ./packages/core/.env
      - ./packages/core/.env.local
      - ./packages/core/.env.test.local
      - ./packages/core/.env.staging.local
      - ./packages/core/.env.production.local