name: Feature request
description: Suggest a new feature
title: "[NEW] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Encre! We appreciate your feedback.
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: Describe your new feature request?
      placeholder: Encre should do this!
      value: "..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/VictorS67/encre)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
